### ISSUE TITLE
Update (Duplicate of #1)

### ISSUE THREAD

**Issue by thewarlok666** [wishhhmaster/CoinTNet#2] opened 2014-05-08 14:20 UTC
This from updated release.zip

![image](https://cloud.githubusercontent.com/assets/6732394/2916490/d8485166-d6bb-11e3-823c-efd8bcf8f5ea.png)

**Comment by wishhhmaster** [comment] 2014-05-14 13:16
Duplicate of #1, closed by commit 1214e90b2a0de20f808ea2a56245d679c7068490

**Closed as completed by wishhhmaster** 2014-05-14 13:16 UTC
Labels: duplicate

**Comment by thewarlok666** [comment] 2014-05-22 21:30
test post please ignore
